source 'https://rubygems.org'
ruby '>= 3.2.0'
group :jekyll_plugins do
    gem 'github-pages', "~> 228"
    gem 'jekyll'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-sitemap'
    gem 'jemoji'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-imagemagick'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'htmlcompressor'
    gem 'htmlbeautifier'
end
